spring.application.name=airBnbApp

##DB Configuration - LocalPostgreSQL
#spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#DB Configuration - Neon Serverless PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-nameless-bread-aep6edl5-pooler.c-2.us-east-2.aws.neon.tech:5432/airbnb-database?sslmode=require
spring.datasource.username=authenticator
spring.datasource.password=npg_3jbrVFce6BYk
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Server default request mapping
server.servlet.context-path=/api/v1